sort_order = [
    "tmux", # show first
    "config",
    "zoxide",  
    "tmuxinator", # show last
]

[default_session]
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"
