[tools]
bat = "latest"
bun = "latest"
claude = "latest"
delta = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
jq = "latest"
lazygit = "latest"
lua = "latest"
node = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
ollama = "latest"
opencode = "latest"
python = "latest"
rg = "latest"
ruby = "3.3.10"
ruff = "latest"
rust = "latest"
stylua = "latest"
terraform = "1.14.3"
tmux = "latest"
zig = "0.15.2"
zoxide = "latest"

[settings]
experimental = true
