[tools]
bat = "latest"
bun = "latest"
cargo = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
lazygit = "latest"
lua = "latest"
node = "latest"
"npm:pyright" = "latest"
ollama = "latest"
opencode = "latest"
python = "latest"
rg = "latest"
ruff = "latest"
rust = "latest"
stylua = "latest"
zig = "0.15.2"
zoxide = "latest"

[settings]
experimental = true
