return {
  { import = "plugins.nvchad" },
  { import = "plugins.conform" },
  { import = "plugins.csv" },
  { import = "plugins.dad_bod" },
  { import = "plugins.godoc" },
  { import = "plugins.nvim_lspconfig" },
  { import = "plugins.nvim_tmux_navigation" },
  { import = "plugins.nvim_tree" },
  { import = "plugins.telescope" },
  { import = "plugins.treesitter" },
  { import = "plugins.trouble" },
  { import = "plugins.snacks" },
  { import = "plugins.sniprun" },
  { import = "plugins.surround" },
}
